version: '3.7'
services:
  # frontend:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     # dockerfile: ./Dockerfile.prod
  #   environment:
  #    - NODE_ENV=dev
  #    - PORT=3000
  #    - CMS_URL=http://localhost:8000
  #   env_file: ./client/.env
  #   ports:
  #     - 8080:80
  #     - "3000:3000"
  #     # - "3000:80"
  #   volumes:
  #     - ./client/src/:/var/www/html/src
  #   stdin_open: true

  backend:
    container_name: sos_api
    build:
      context: cms
      dockerfile: Dockerfile
    env_file: ./cms/.env
    ports:
      - 8000:8000
    volumes:
      - ./cms:/var/www
    depends_on:
      - db
    networks:
      - control-hq

  db:
    container_name: sos_db
    # build:
    #   context: cms
    #   dockerfile: Dockerfile
    image: postgres:11
    restart: always
    env_file: ./cms/.env
    volumes:
     - .data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - control-hq

networks:
  control-hq:
