version: '3.7'
services:
  # frontend:
  #   image: antoniopapa1991/admin-frontend
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - control-hq
  #   environment:
  #     - PORT:8000


  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_HOST: "db"
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - control-hq

  db:
    container_name: admin_db
    image: postgres:11
    restart: always
    env_file: .env
    volumes:
     - .data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - control-hq

networks:
  control-hq:
